export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const CREATE_GUIDE_SUCCESS = 'CREATE_GUIDE_SUCCESS';
export const CREATE_GUIDE_FAILURE = 'CREATE_GUIDE_FAILURE';
